### ISSUE TITLE
History Screen

### ISSUE THREAD

**Issue by akimcse** [Donut-DONationUTile/Donut_Android#63]
- [x] implement new history screen #73 
- [x] link new history screen with my page screen #73 
- [x] implement new history detail screen #74
