### ISSUE TITLE
Integrate APIs in Wallet Screen 

### ISSUE THREAD

**Issue by akimcse** [Donut-DONationUTile/Donut_Android#68]
- [x] implement giverHomeFragment imminent rcecycerView with data #83
- [x] change impending recyclerView ui #83
- [ ] show wallet detail screen #84
