### ISSUE TITLE
Integrate Report APIs

### ISSUE THREAD

**Issue by akimcse** [Donut-DONationUTile/Donut_Android#85]
- [x] implement report unused item #91
- [x] implement report as used item #91
- [x] implement report as cheated item #91
